In [2]:
import pandas as pd
import numpy as np

In [3]:
ipl=pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\ipl data analytics project\Datasets\IPL_Data.csv")
ipl.head()

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,13.0,0.0,0/13 v MI,0.0,0.0,NaN,13.00,NaN,1.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,2.0,1560.0,76.0,4/21 v RCB,4.0,0.0,20.52,8.21,15.0,50.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,0.0,66.0,4.0,1/7 v DC,0.0,0.0,16.50,8.25,12.0,6.0

In [5]:
ipl.shape

(237, 39)

In [8]:
ipl.columns

Index(['Name', 'Team', 'Url', 'Type', 'ValueinCR', 'Full Name', 'Born', 'Age',
       'National Side', 'Batting Style', 'Bowling', 'Sport', 'MatchPlayed',
       'InningsBatted', 'NotOuts', 'RunsScored', 'HighestInnScore', '100s',
       '50s', '4s', '6s', 'BattingAVG', 'BattingS/R', 'CatchesTaken',
       'StumpingsMade', 'Ducks', 'R/O', 'InningsBowled', 'Overs', 'Maidens',
       'RunsConceded', 'Wickets', 'Best', '3s', '5s', 'BowlingAVG',
       'EconomyRate', 'S/R', 'Mtc'],
      dtype='object')

In [9]:
ipl.isnull().sum()

Name                 0
Team                 0
Url                  0
Type                 0
ValueinCR            0
Full Name            6
Born                 6
Age                  6
National Side        6
Batting Style       10
Bowling             31
Sport              111
MatchPlayed         75
InningsBatted       75
NotOuts             75
RunsScored          84
HighestInnScore     84
100s                75
50s                 75
4s                  75
6s                  75
BattingAVG          92
BattingS/R          75
CatchesTaken        92
StumpingsMade       92
Ducks               76
R/O                 76
InningsBowled      115
Overs              115
Maidens            115
RunsConceded       115
Wickets            115
Best               115
3s                 115
5s                 115
BowlingAVG         132
EconomyRate        115
S/R                132
Mtc                115
dtype: int64

In [10]:
ipl['Type'].value_counts()

Type
All-Rounder       87
Bowler            77
Batsman           46
Wicket-Keeper     26
Wicket-keeper      1
Name: count, dtype: int64

In [14]:
ipl['Type'] = ipl['Type'].replace({
    'Wicket-keeper':'Wicket-Keeper'
})

In [15]:
ipl['Type'].value_counts()

Type
All-Rounder       87
Bowler            77
Batsman           46
Wicket-Keeper     26
Wicket-keeper      1
Name: count, dtype: int64

In [16]:
ipl['Type'].unique()

array(['Batsman ', 'All-Rounder ', 'Bowler ', 'Wicket-Keeper ',
       'Wicket-keeper '], dtype=object)

In [17]:
ipl['Type'] = ipl['Type'].str.strip()

In [18]:
ipl['Type'] = ipl['Type'].replace({
    'Wicket-keeper':'Wicket-Keeper'
})

In [19]:
ipl['Type'].value_counts()

Type
All-Rounder      87
Bowler           77
Batsman          46
Wicket-Keeper    27
Name: count, dtype: int64

In [22]:
ipl.duplicated().sum()

np.int64(0)

In [23]:
auction_df = ipl[
[
'Name',
'Team',
'Type',
'ValueinCR',
'RunsScored',
'BattingAVG',
'BattingS/R',
'Wickets',
'BowlingAVG',
'EconomyRate'
]
]

In [24]:
auction_df.head()

,Name,Team,Type,ValueinCR,RunsScored,BattingAVG,BattingS/R,Wickets,BowlingAVG,EconomyRate
0,Mayank Agarwal,PBKS,Batsman,12.00,2131.0,23.41,135.47,NaN,NaN,NaN
1,Liam Livingstone,PBKS,All-Rounder,11.50,112.0,14.00,125.84,0.0,NaN,13.00
2,Kagiso Rabada,PBKS,Bowler,9.25,138.0,13.80,102.98,76.0,20.52,8.21
3,Shahrukh Khan,PBKS,All-Rounder,9.00,153.0,21.85,134.21,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,Batsman,8.25,5784.0,34.84,126.64,4.0,16.50,8.25

In [25]:
auction_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         237 non-null    object
 1   Team         237 non-null    object
 2   Type         237 non-null    object
 3   ValueinCR    237 non-null    float64
 4   RunsScored   153 non-null    float64
 5   BattingAVG   145 non-null    float64
 6   BattingS/R   162 non-null    float64
 7   Wickets      122 non-null    float64
 8   BowlingAVG   105 non-null    float64
 9   EconomyRate  122 non-null    float64
dtypes: float64(7), object(3)
memory usage: 18.6+ KB

In [26]:
batsmen_df = auction_df[auction_df['Type']=='Batsman'].copy()

bowler_df = auction_df[auction_df['Type']=='Bowler'].copy()

allrounder_df = auction_df[auction_df['Type']=='All-Rounder'].copy()

wk_df = auction_df[auction_df['Type']=='Wicket-Keeper'].copy()

In [27]:
print("Batsmen:", batsmen_df.shape)

print("Bowlers:", bowler_df.shape)

print("All-Rounders:", allrounder_df.shape)

print("Wicket Keepers:", wk_df.shape)

Batsmen: (46, 10)
Bowlers: (77, 10)
All-Rounders: (87, 10)
Wicket Keepers: (27, 10)

In [28]:
batsmen_df[['RunsScored','BattingAVG','BattingS/R']].describe()

        RunsScored  BattingAVG  BattingS/R
count    30.000000   30.000000   30.000000
mean   2032.600000   28.182667  129.236333
std    1913.727318    8.056596   10.273427
min      16.000000   11.000000  101.310000
25%     376.000000   23.622500  123.985000
50%    1448.500000   29.050000  130.045000
75%    2795.000000   31.637500  135.650000
max    6283.000000   46.610000  151.170000

In [29]:
batsmen_score_df = batsmen_df.dropna(
    subset=['RunsScored','BattingAVG','BattingS/R']
).copy()

In [30]:
batsmen_score_df.shape

(30, 10)

In [31]:
batsmen_score_df['Runs_Norm'] = (
    batsmen_score_df['RunsScored'] /
    batsmen_score_df['RunsScored'].max()
)

batsmen_score_df['Avg_Norm'] = (
    batsmen_score_df['BattingAVG'] /
    batsmen_score_df['BattingAVG'].max()
)

batsmen_score_df['SR_Norm'] = (
    batsmen_score_df['BattingS/R'] /
    batsmen_score_df['BattingS/R'].max()
)

In [32]:
batsmen_score_df['PerformanceScore'] = (
    0.50 * batsmen_score_df['Runs_Norm'] +
    0.25 * batsmen_score_df['Avg_Norm'] +
    0.25 * batsmen_score_df['SR_Norm']
) * 100

In [33]:
batsmen_score_df[
    ['Name','Team','ValueinCR','PerformanceScore']
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(10)

                 Name  Team  ValueinCR  PerformanceScore
72        Virat Kohli   RCB      15.00         91.543761
175      David Warner    DC       6.25         88.816615
4      Shikhar Dhawan  PBKS       8.25         85.659253
94       Rohit Sharma    MI      16.00         82.934223
128     Robin Uthappa   CSK       2.00         74.087426
157    Ajinkya Rahane   KKR       1.00         68.333808
201     Manish Pandey   LSG       4.60         64.933958
77     Faf du Plessis   RCB       7.00         63.774872
25    Kane Williamson   SRH      14.00         58.216405
99   Suryakumar Yadav    MI       8.00         56.573877

In [34]:
batsmen_score_df['ValueIndex'] = (
    batsmen_score_df['PerformanceScore'] /
    batsmen_score_df['ValueinCR']
)

In [35]:
batsmen_score_df[
    ['Name','ValueinCR','PerformanceScore','ValueIndex']
].sort_values(
    by='ValueIndex',
    ascending=False
).head(10)

                 Name  ValueinCR  PerformanceScore  ValueIndex
213       Manan Vohra       0.20         42.011230  210.056150
43        Priyam Garg       0.20         27.809174  139.045869
114  Anmolpreet Singh       0.20         27.608430  138.042148
157    Ajinkya Rahane       1.00         68.333808   68.333808
159       Rinku Singh       0.55         23.267102   42.303823
183     Mandeep Singh       1.10         45.654030   41.503664
128     Robin Uthappa       2.00         74.087426   37.043713
61         Karun Nair       1.40         46.017799   32.869857
155        Alex Hales       1.50         35.146106   23.430737
226         Jason Roy       2.00         39.992413   19.996206

In [36]:
batsmen_score_df[['Name','RunsScored']].sort_values(
    by='RunsScored',
    ascending=False
).head()

               Name  RunsScored
72      Virat Kohli      6283.0
4    Shikhar Dhawan      5784.0
94     Rohit Sharma      5611.0
175    David Warner      5449.0
128   Robin Uthappa      4722.0

In [37]:
qualified_batsmen = batsmen_score_df[
    batsmen_score_df['RunsScored'] >= 1000
].copy()

In [38]:
qualified_batsmen.shape

(19, 15)

In [39]:
qualified_batsmen['ValueIndex'] = (
    qualified_batsmen['PerformanceScore'] /
    qualified_batsmen['ValueinCR']
)

In [40]:
qualified_batsmen[
    ['Name','RunsScored','ValueinCR',
     'PerformanceScore','ValueIndex']
].sort_values(
    by='ValueIndex',
    ascending=False
).head(15)

                 Name  RunsScored  ValueinCR  PerformanceScore  ValueIndex
213       Manan Vohra      1054.0       0.20         42.011230  210.056150
157    Ajinkya Rahane      3941.0       1.00         68.333808   68.333808
183     Mandeep Singh      1674.0       1.10         45.654030   41.503664
128     Robin Uthappa      4722.0       2.00         74.087426   37.043713
61         Karun Nair      1480.0       1.40         46.017799   32.869857
222      David Miller      1974.0       3.00         55.931061   18.643687
175      David Warner      5449.0       6.25         88.816615   14.210658
201     Manish Pandey      3560.0       4.60         64.933958   14.116078
4      Shikhar Dhawan      5784.0       8.25         85.659253   10.382940
77     Faf du Plessis      2935.0       7.00         63.774872    9.110696
99   Suryakumar Yadav      2341.0       8.00         56.573877    7.071735
172      Prithvi Shaw      1305.0       7.50         47.785102    6.371347
72        Virat Kohli      6283.0      15.00         91.543761    6.102917
218      Shubman Gill      1417.0       8.00         48.502587    6.062823
28     Rahul Tripathi      1385.0       8.50         47.579539    5.597593

In [41]:
qualified_batsmen[
    ['Name','RunsScored','ValueinCR','PerformanceScore']
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(15)

                 Name  RunsScored  ValueinCR  PerformanceScore
72        Virat Kohli      6283.0      15.00         91.543761
175      David Warner      5449.0       6.25         88.816615
4      Shikhar Dhawan      5784.0       8.25         85.659253
94       Rohit Sharma      5611.0      16.00         82.934223
128     Robin Uthappa      4722.0       2.00         74.087426
157    Ajinkya Rahane      3941.0       1.00         68.333808
201     Manish Pandey      3560.0       4.60         64.933958
77     Faf du Plessis      2935.0       7.00         63.774872
25    Kane Williamson      1885.0      14.00         58.216405
99   Suryakumar Yadav      2341.0       8.00         56.573877
144      Shreyas Iyer      2375.0      12.25         56.379987
222      David Miller      1974.0       3.00         55.931061
0      Mayank Agarwal      2131.0      12.00         51.918363
218      Shubman Gill      1417.0       8.00         48.502587
172      Prithvi Shaw      1305.0       7.50         47.785102

In [42]:
qualified_batsmen['Score_Category'] = pd.cut(
    qualified_batsmen['PerformanceScore'],
    bins=[0,50,75,100],
    labels=['Average','Good','Elite']
)

In [43]:
qualified_batsmen[['Name','PerformanceScore','Score_Category']].head()

               Name  PerformanceScore Score_Category
0    Mayank Agarwal         51.918363           Good
4    Shikhar Dhawan         85.659253          Elite
25  Kane Williamson         58.216405           Good
28   Rahul Tripathi         47.579539        Average
61       Karun Nair         46.017799        Average

In [44]:
qualified_batsmen[['Name','PerformanceScore','Score_Category']].head()

               Name  PerformanceScore Score_Category
0    Mayank Agarwal         51.918363           Good
4    Shikhar Dhawan         85.659253          Elite
25  Kane Williamson         58.216405           Good
28   Rahul Tripathi         47.579539        Average
61       Karun Nair         46.017799        Average

In [46]:
qualified_batsmen['Price_Category'] = pd.cut(
    qualified_batsmen['ValueinCR'],
    bins=[0,5,10,20],
    labels=['Cheap','Moderate','Expensive']
)

In [47]:
qualified_batsmen[['Name','ValueinCR','Price_Category']].head()

               Name  ValueinCR Price_Category
0    Mayank Agarwal      12.00      Expensive
4    Shikhar Dhawan       8.25       Moderate
25  Kane Williamson      14.00      Expensive
28   Rahul Tripathi       8.50       Moderate
61       Karun Nair       1.40          Cheap

In [48]:
qualified_batsmen[['Name',
                   'PerformanceScore',
                   'Score_Category',
                   'ValueinCR',
                   'Price_Category']].head(15)

,Name,PerformanceScore,Score_Category,ValueinCR,Price_Category
0,Mayank Agarwal,51.918363,Good,12.00,Expensive
4,Shikhar Dhawan,85.659253,Elite,8.25,Moderate
25,Kane Williamson,58.216405,Good,14.00,Expensive
28,Rahul Tripathi,47.579539,Average,8.50,Moderate
61,Karun Nair,46.017799,Average,1.40,Cheap
72,Virat Kohli,91.543761,Elite,15.00,Expensive
77,Faf du Plessis,63.774872,Good,7.00,Moderate
94,Rohit Sharma,82.934223,Elite,16.00,Expensive
99,Suryakumar Yadav,56.573877,Good,8.00,Moderate
128,Robin Uthappa,74.087426,Good,2.00,Cheap
144,Shreyas Iyer,56.379987,Good,12.25,Expensive
157,Ajinkya Rahane,68.333808,Good,1.00,Cheap
172,Prithvi Shaw,47.785102,Average,7.50,Moderate
175,David Warner,88.816615,Elite,6.25,Moderate
183,Mandeep Singh,45.654030,Average,1.10,Cheap

In [49]:
def classify_player(row):

    if row['Score_Category'] == 'Elite' and row['Price_Category'] == 'Cheap':
        return 'Hidden Gem'

    elif row['Score_Category'] == 'Elite' and row['Price_Category'] == 'Moderate':
        return 'Strong Buy'

    elif row['Score_Category'] == 'Elite' and row['Price_Category'] == 'Expensive':
        return 'Star Player'

    elif row['Score_Category'] == 'Average' and row['Price_Category'] == 'Expensive':
        return 'Overpriced'

    elif row['Score_Category'] == 'Good' and row['Price_Category'] == 'Cheap':
        return 'Value Pick'

    else:
        return 'Neutral'

qualified_batsmen['Recommendation'] = qualified_batsmen.apply(
    classify_player,
    axis=1
)

In [50]:
qualified_batsmen[
[
'Name',
'PerformanceScore',
'ValueinCR',
'Recommendation'
]
].sort_values(
by='PerformanceScore',
ascending=False
)

                 Name  PerformanceScore  ValueinCR Recommendation
72        Virat Kohli         91.543761      15.00    Star Player
175      David Warner         88.816615       6.25     Strong Buy
4      Shikhar Dhawan         85.659253       8.25     Strong Buy
94       Rohit Sharma         82.934223      16.00    Star Player
128     Robin Uthappa         74.087426       2.00     Value Pick
157    Ajinkya Rahane         68.333808       1.00     Value Pick
201     Manish Pandey         64.933958       4.60     Value Pick
77     Faf du Plessis         63.774872       7.00        Neutral
25    Kane Williamson         58.216405      14.00        Neutral
99   Suryakumar Yadav         56.573877       8.00        Neutral
144      Shreyas Iyer         56.379987      12.25        Neutral
222      David Miller         55.931061       3.00     Value Pick
0      Mayank Agarwal         51.918363      12.00        Neutral
218      Shubman Gill         48.502587       8.00        Neutral
172      Prithvi Shaw         47.785102       7.50        Neutral
28     Rahul Tripathi         47.579539       8.50        Neutral
61         Karun Nair         46.017799       1.40        Neutral
183     Mandeep Singh         45.654030       1.10        Neutral
213       Manan Vohra         42.011230       0.20        Neutral

In [51]:
qualified_batsmen['MedianScore'] = qualified_batsmen['PerformanceScore'].median()

qualified_batsmen['MedianPrice'] = qualified_batsmen['ValueinCR'].median()

In [52]:
qualified_batsmen[['MedianScore','MedianPrice']].head(1)

   MedianScore  MedianPrice
0    56.573877          7.5

In [53]:
def auction_category(row):

    if row['PerformanceScore'] >= 56.57 and row['ValueinCR'] < 7.5:
        return 'Hidden Gem'

    elif row['PerformanceScore'] >= 56.57 and row['ValueinCR'] >= 7.5:
        return 'Star Player'

    elif row['PerformanceScore'] < 56.57 and row['ValueinCR'] < 7.5:
        return 'Budget Pick'

    else:
        return 'Overpriced'


qualified_batsmen['AuctionCategory'] = qualified_batsmen.apply(
    auction_category,
    axis=1
)

In [54]:
qualified_batsmen[
[
'Name',
'PerformanceScore',
'ValueinCR',
'AuctionCategory'
]
].sort_values(
by='PerformanceScore',
ascending=False
)

                 Name  PerformanceScore  ValueinCR AuctionCategory
72        Virat Kohli         91.543761      15.00     Star Player
175      David Warner         88.816615       6.25      Hidden Gem
4      Shikhar Dhawan         85.659253       8.25     Star Player
94       Rohit Sharma         82.934223      16.00     Star Player
128     Robin Uthappa         74.087426       2.00      Hidden Gem
157    Ajinkya Rahane         68.333808       1.00      Hidden Gem
201     Manish Pandey         64.933958       4.60      Hidden Gem
77     Faf du Plessis         63.774872       7.00      Hidden Gem
25    Kane Williamson         58.216405      14.00     Star Player
99   Suryakumar Yadav         56.573877       8.00     Star Player
144      Shreyas Iyer         56.379987      12.25      Overpriced
222      David Miller         55.931061       3.00     Budget Pick
0      Mayank Agarwal         51.918363      12.00      Overpriced
218      Shubman Gill         48.502587       8.00      Overpriced
172      Prithvi Shaw         47.785102       7.50      Overpriced
28     Rahul Tripathi         47.579539       8.50      Overpriced
61         Karun Nair         46.017799       1.40     Budget Pick
183     Mandeep Singh         45.654030       1.10     Budget Pick
213       Manan Vohra         42.011230       0.20     Budget Pick

In [55]:
bowler_score_df = bowler_df.dropna(
    subset=['Wickets','BowlingAVG','EconomyRate']
).copy()

In [56]:
bowler_score_df.shape

(53, 10)

In [57]:
bowler_score_df[
['Name','Wickets','BowlingAVG','EconomyRate']
].head()

              Name  Wickets  BowlingAVG  EconomyRate
2    Kagiso Rabada     76.0       20.52         8.21
7     Rahul Chahar     43.0       25.97         7.44
8   Arshdeep Singh     30.0       22.30         8.78
12    Nathan Ellis      1.0       90.00         8.18
16  Sandeep Sharma    112.0       25.43         7.77

In [58]:
bowler_score_df[
['Wickets','BowlingAVG','EconomyRate']
].describe()

          Wickets  BowlingAVG  EconomyRate
count   53.000000   53.000000    53.000000
mean    40.811321   32.080000     8.472642
std     37.108498   12.122189     0.977574
min      1.000000   14.500000     6.330000
25%     13.000000   25.260000     7.860000
50%     30.000000   29.500000     8.380000
75%     58.000000   37.160000     8.880000
max    142.000000   90.000000    11.380000

In [59]:
bowler_score_df['Wickets_Norm'] = (
    bowler_score_df['Wickets'] /
    bowler_score_df['Wickets'].max()
)

bowler_score_df['BowlingAVG_Norm'] = (
    bowler_score_df['BowlingAVG'].min() /
    bowler_score_df['BowlingAVG']
)

bowler_score_df['Economy_Norm'] = (
    bowler_score_df['EconomyRate'].min() /
    bowler_score_df['EconomyRate']
)

In [60]:
bowler_score_df[
[
'Name',
'Wickets_Norm',
'BowlingAVG_Norm',
'Economy_Norm'
]
].head()

              Name  Wickets_Norm  BowlingAVG_Norm  Economy_Norm
2    Kagiso Rabada      0.535211         0.706628      0.771011
7     Rahul Chahar      0.302817         0.558337      0.850806
8   Arshdeep Singh      0.211268         0.650224      0.720957
12    Nathan Ellis      0.007042         0.161111      0.773839
16  Sandeep Sharma      0.788732         0.570193      0.814672

In [61]:
bowler_score_df['PerformanceScore'] = (
    0.50 * bowler_score_df['Wickets_Norm'] +
    0.30 * bowler_score_df['Economy_Norm'] +
    0.20 * bowler_score_df['BowlingAVG_Norm']
) * 100

In [62]:
bowler_score_df[
[
'Name',
'ValueinCR',
'Wickets',
'EconomyRate',
'PerformanceScore'
]
].sort_values(
by='PerformanceScore',
ascending=False
).head(15)

                    Name  ValueinCR  Wickets  EconomyRate  PerformanceScore
31     Bhuvneshwar Kumar       4.20    142.0         7.30         87.494300
54      Yuzvendra Chahal       6.50    139.0         7.59         86.979583
96        Jasprit Bumrah      12.00    130.0         7.42         83.948985
214          Rashid Khan      15.00     93.0         6.33         76.858401
16        Sandeep Sharma       0.50    112.0         7.77         75.280628
152          Umesh Yadav       2.00    119.0         8.51         73.860496
2          Kagiso Rabada       9.25     76.0         8.21         64.023446
106       Jaydev Unadkat       1.30     85.0         8.74         61.184204
52           Trent Boult       8.00     76.0         8.39         60.510021
219       Mohammed Shami       6.25     79.0         8.62         59.386538
88           Karn Sharma       0.50     59.0         7.90         55.443121
59   Nathan Coulter-Nile       2.00     48.0         7.52         55.390033
170       Shardul Thakur      10.75     67.0         8.89         55.361818
120        Deepak Chahar      14.00     59.0         7.80         55.059116
147   Varun Chakravarthy       8.00     36.0         6.82         52.966983

In [63]:
bowler_score_df['PerformanceScore'].median()

44.95330340771116

In [64]:
bowler_score_df['ValueinCR'].median()

2.0

In [65]:
def bowler_category(row):

    if row['PerformanceScore'] >= 44.95 and row['ValueinCR'] < 2:
        return 'Hidden Gem'

    elif row['PerformanceScore'] >= 44.95 and row['ValueinCR'] >= 2:
        return 'Star Player'

    elif row['PerformanceScore'] < 44.95 and row['ValueinCR'] < 2:
        return 'Budget Pick'

    else:
        return 'Overpriced'


bowler_score_df['AuctionCategory'] = bowler_score_df.apply(
    bowler_category,
    axis=1
)

In [66]:
bowler_score_df[
[
'Name',
'PerformanceScore',
'ValueinCR',
'AuctionCategory'
]
].sort_values(
by='PerformanceScore',
ascending=False
).head(20)

                    Name  PerformanceScore  ValueinCR AuctionCategory
31     Bhuvneshwar Kumar         87.494300       4.20     Star Player
54      Yuzvendra Chahal         86.979583       6.50     Star Player
96        Jasprit Bumrah         83.948985      12.00     Star Player
214          Rashid Khan         76.858401      15.00     Star Player
16        Sandeep Sharma         75.280628       0.50      Hidden Gem
152          Umesh Yadav         73.860496       2.00     Star Player
2          Kagiso Rabada         64.023446       9.25     Star Player
106       Jaydev Unadkat         61.184204       1.30      Hidden Gem
52           Trent Boult         60.510021       8.00     Star Player
219       Mohammed Shami         59.386538       6.25     Star Player
88           Karn Sharma         55.443121       0.50      Hidden Gem
59   Nathan Coulter-Nile         55.390033       2.00     Star Player
170       Shardul Thakur         55.361818      10.75     Star Player
120        Deepak Chahar         55.059116      14.00     Star Player
147   Varun Chakravarthy         52.966983       8.00     Star Player
87         Siddarth Kaul         52.473323       0.75      Hidden Gem
7           Rahul Chahar         51.831769       5.25     Star Player
40         Shreyas Gopal         51.716956       0.75      Hidden Gem
174        Anrich Nortje         50.907283       6.50     Star Player
78        Mohammed Siraj         50.357198       7.00     Star Player

In [67]:
allrounder_score_df = allrounder_df.dropna(
    subset=[
        'RunsScored',
        'BattingAVG',
        'BattingS/R',
        'Wickets',
        'BowlingAVG',
        'EconomyRate'
    ]
).copy()

In [68]:
allrounder_score_df[
[
'Name',
'RunsScored',
'Wickets',
'ValueinCR'
]
].head()

                   Name  RunsScored  Wickets  ValueinCR
14         Rishi Dhawan       153.0     18.0       0.55
27    Washington Sundar       217.0     27.0       8.75
30      Abhishek Sharma       241.0      7.0       6.50
32         Marco Jansen         0.0      2.0       4.20
55  Ravichandran Ashwin       456.0    145.0       5.00

In [69]:
allrounder_score_df.shape

(43, 10)

In [70]:
allrounder_score_df[
[
'RunsScored',
'BattingAVG',
'BattingS/R',
'Wickets',
'BowlingAVG',
'EconomyRate'
]
].describe()

,RunsScored,BattingAVG,BattingS/R,Wickets,BowlingAVG,EconomyRate
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000
mean,585.604651,18.055581,121.025116,33.511628,37.246279,8.040930
std,745.850653,9.229184,33.247231,42.925390,23.891685,0.833415
min,0.000000,0.000000,0.000000,1.000000,15.110000,6.740000
25%,66.000000,11.060000,111.195000,5.500000,24.515000,7.290000
50%,225.000000,17.210000,126.240000,16.000000,30.130000,8.180000
75%,849.500000,24.090000,139.215000,40.000000,37.335000,8.600000
max,3268.000000,41.110000,178.570000,167.000000,153.000000,9.960000

In [71]:
allrounder_score_df['Runs_Norm'] = (
    allrounder_score_df['RunsScored'] /
    allrounder_score_df['RunsScored'].max()
)

allrounder_score_df['BatAvg_Norm'] = (
    allrounder_score_df['BattingAVG'] /
    allrounder_score_df['BattingAVG'].max()
)

allrounder_score_df['BatSR_Norm'] = (
    allrounder_score_df['BattingS/R'] /
    allrounder_score_df['BattingS/R'].max()
)

In [72]:
allrounder_score_df['Wickets_Norm'] = (
    allrounder_score_df['Wickets'] /
    allrounder_score_df['Wickets'].max()
)

allrounder_score_df['BowlAvg_Norm'] = (
    allrounder_score_df['BowlingAVG'].min() /
    allrounder_score_df['BowlingAVG']
)

allrounder_score_df['Economy_Norm'] = (
    allrounder_score_df['EconomyRate'].min() /
    allrounder_score_df['EconomyRate']
)

In [73]:
allrounder_score_df[
[
'Name',
'Runs_Norm',
'BatAvg_Norm',
'BatSR_Norm',
'Wickets_Norm',
'BowlAvg_Norm',
'Economy_Norm'
]
].head()

,Name,Runs_Norm,BatAvg_Norm,BatSR_Norm,Wickets_Norm,BowlAvg_Norm,Economy_Norm
14,Rishi Dhawan,0.046818,0.531501,0.634653,0.107784,0.425035,0.857506
27,Washington Sundar,0.066401,0.329847,0.623173,0.161677,0.470570,0.972583
30,Abhishek Sharma,0.073745,0.418633,0.780086,0.041916,0.601034,0.842500
32,Marco Jansen,0.000000,0.000000,0.000000,0.011976,0.671556,0.898667
55,Ravichandran Ashwin,0.139535,0.270494,0.615333,0.868263,0.543525,0.975398

In [74]:
allrounder_score_df['PerformanceScore'] = (
    0.20 * allrounder_score_df['Runs_Norm'] +
    0.10 * allrounder_score_df['BatAvg_Norm'] +
    0.10 * allrounder_score_df['BatSR_Norm'] +
    0.30 * allrounder_score_df['Wickets_Norm'] +
    0.15 * allrounder_score_df['BowlAvg_Norm'] +
    0.15 * allrounder_score_df['Economy_Norm']
) * 100

In [75]:
allrounder_score_df[
[
'Name',
'ValueinCR',
'RunsScored',
'Wickets',
'PerformanceScore'
]
].sort_values(
by='PerformanceScore',
ascending=False
).head(15)

                    Name  ValueinCR  RunsScored  Wickets  PerformanceScore
125         Dwayne Bravo       4.40      1537.0    167.0         73.697199
119      Ravindra Jadeja      16.00      2386.0    127.0         72.017066
151         Sunil Narine       6.00       954.0    143.0         68.623470
100       Kieron Pollard       6.00      3268.0     65.0         66.041469
55   Ravichandran Ashwin       5.00       456.0    145.0         60.480716
145        Andre Russell      12.00      1700.0     72.0         60.236556
171           Axar Patel       9.00       953.0     95.0         55.923672
215        Hardik Pandya      15.00      1476.0     42.0         50.254425
197        Krunal Pandya       8.25      1143.0     51.0         49.732612
146          Nitish Rana       8.00      1820.0      7.0         49.621767
73         Glenn Maxwell      11.00      2018.0     22.0         48.214214
74         Harshal Patel      10.75       187.0     78.0         46.931158
98          Jofra Archer       8.00       195.0     46.0         46.722067
122            Moeen Ali       8.00       666.0     16.0         43.245498
195       Marcus Stoinis       9.20       914.0     30.0         42.982998

In [76]:
allrounder_score_df['PerformanceScore'].median()

39.18038172145346

In [77]:
allrounder_score_df['ValueinCR'].median()

5.0

In [78]:
def allrounder_category(row):

    if row['PerformanceScore'] >= 39.18 and row['ValueinCR'] < 5:
        return 'Hidden Gem'

    elif row['PerformanceScore'] >= 39.18 and row['ValueinCR'] >= 5:
        return 'Star Player'

    elif row['PerformanceScore'] < 39.18 and row['ValueinCR'] < 5:
        return 'Budget Pick'

    else:
        return 'Overpriced'


allrounder_score_df['AuctionCategory'] = (
    allrounder_score_df.apply(allrounder_category, axis=1)
)

In [79]:
allrounder_score_df[
[
'Name',
'PerformanceScore',
'ValueinCR',
'AuctionCategory'
]
].sort_values(
by='PerformanceScore',
ascending=False
).head(20)

                     Name  PerformanceScore  ValueinCR AuctionCategory
125          Dwayne Bravo         73.697199       4.40      Hidden Gem
119       Ravindra Jadeja         72.017066      16.00     Star Player
151          Sunil Narine         68.623470       6.00     Star Player
100        Kieron Pollard         66.041469       6.00     Star Player
55    Ravichandran Ashwin         60.480716       5.00     Star Player
145         Andre Russell         60.236556      12.00     Star Player
171            Axar Patel         55.923672       9.00     Star Player
215         Hardik Pandya         50.254425      15.00     Star Player
197         Krunal Pandya         49.732612       8.25     Star Player
146           Nitish Rana         49.621767       8.00     Star Player
73          Glenn Maxwell         48.214214      11.00     Star Player
74          Harshal Patel         46.931158      10.75     Star Player
98           Jofra Archer         46.722067       8.00     Star Player
122             Moeen Ali         43.245498       8.00     Star Player
195        Marcus Stoinis         42.982998       9.20     Star Player
148        Venkatesh Iyer         42.318121       8.00     Star Player
150           Pat Cummins         41.235867       7.25     Star Player
232  Gurkeerat Singh Mann         41.220650       0.50      Hidden Gem
129      Mitchell Santner         40.542897       1.90      Hidden Gem
196          Jason Holder         40.188007       8.75     Star Player

In [80]:
batsmen_final = qualified_batsmen[
['Name','Type','ValueinCR','PerformanceScore']
].copy()

In [81]:
bowlers_final = bowler_score_df[
['Name','Type','ValueinCR','PerformanceScore']
].copy()

In [82]:
allrounders_final = allrounder_score_df[
['Name','Type','ValueinCR','PerformanceScore']
].copy()

In [83]:
master_df = pd.concat([
    batsmen_final,
    bowlers_final,
    allrounders_final
], ignore_index=True)

In [84]:
master_df.shape

(115, 4)

In [85]:
master_df.head()

              Name     Type  ValueinCR  PerformanceScore
0   Mayank Agarwal  Batsman      12.00         51.918363
1   Shikhar Dhawan  Batsman       8.25         85.659253
2  Kane Williamson  Batsman      14.00         58.216405
3   Rahul Tripathi  Batsman       8.50         47.579539
4       Karun Nair  Batsman       1.40         46.017799

In [86]:
master_df['Type'].value_counts()

Type
Bowler         53
All-Rounder    43
Batsman        19
Name: count, dtype: int64

In [87]:
master_df.sort_values(
    by='PerformanceScore',
    ascending=False
).head(20)

                 Name         Type  ValueinCR  PerformanceScore
5         Virat Kohli      Batsman      15.00         91.543761
13       David Warner      Batsman       6.25         88.816615
25  Bhuvneshwar Kumar       Bowler       4.20         87.494300
33   Yuzvendra Chahal       Bowler       6.50         86.979583
1      Shikhar Dhawan      Batsman       8.25         85.659253
42     Jasprit Bumrah       Bowler      12.00         83.948985
7        Rohit Sharma      Batsman      16.00         82.934223
67        Rashid Khan       Bowler      15.00         76.858401
23     Sandeep Sharma       Bowler       0.50         75.280628
9       Robin Uthappa      Batsman       2.00         74.087426
54        Umesh Yadav       Bowler       2.00         73.860496
90       Dwayne Bravo  All-Rounder       4.40         73.697199
88    Ravindra Jadeja  All-Rounder      16.00         72.017066
99       Sunil Narine  All-Rounder       6.00         68.623470
11     Ajinkya Rahane      Batsman       1.00         68.333808
85     Kieron Pollard  All-Rounder       6.00         66.041469
15      Manish Pandey      Batsman       4.60         64.933958
19      Kagiso Rabada       Bowler       9.25         64.023446
6      Faf du Plessis      Batsman       7.00         63.774872
45     Jaydev Unadkat       Bowler       1.30         61.184204

In [88]:
wk_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 5 to 227
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         27 non-null     object
 1   Team         27 non-null     object
 2   Type         27 non-null     object
 3   ValueinCR    27 non-null     float64
 4   RunsScored   21 non-null     float64
 5   BattingAVG   21 non-null     float64
 6   BattingS/R   21 non-null     float64
 7   Wickets      1 non-null      float64
 8   BowlingAVG   1 non-null      float64
 9   EconomyRate  1 non-null      float64
dtypes: float64(7), object(3)
memory usage: 2.3+ KB

In [89]:
wk_df.head()

,Name,Team,Type,ValueinCR,RunsScored,BattingAVG,BattingS/R,Wickets,BowlingAVG,EconomyRate
5,Jonny Bairstow,PBKS,Wicket-Keeper,6.75,1038.0,41.52,142.19,NaN,NaN,NaN
13,Prabhsimran Singh,PBKS,Wicket-Keeper,0.60,50.0,10.00,90.90,NaN,NaN,NaN
22,Jitesh Sharma,PBKS,Wicket-Keeper,0.20,NaN,NaN,NaN,NaN,NaN,NaN
26,Nicholas Pooran,SRH,Wicket-Keeper,10.75,606.0,22.44,154.98,NaN,NaN,NaN
39,Glenn Phillips,SRH,Wicket-Keeper,1.50,26.0,13.00,78.78,1.0,20.0,10.0

In [90]:
wk_score_df = wk_df.dropna(
    subset=['RunsScored','BattingAVG','BattingS/R']
).copy()

In [91]:
wk_score_df.shape

(21, 10)

In [92]:
wk_score_df[
['RunsScored','BattingAVG','BattingS/R']
].describe()

        RunsScored  BattingAVG  BattingS/R
count    21.000000   21.000000   21.000000
mean   1507.333333   23.854286  113.497143
std    1581.178527   13.691259   39.330496
min       0.000000    0.000000    0.000000
25%      33.000000   13.000000   90.900000
50%    1038.000000   25.770000  129.720000
75%    2498.000000   35.140000  136.330000
max    4746.000000   47.430000  154.980000

In [93]:
wk_score_df['Runs_Norm'] = (
    wk_score_df['RunsScored'] /
    wk_score_df['RunsScored'].max()
)

wk_score_df['Avg_Norm'] = (
    wk_score_df['BattingAVG'] /
    wk_score_df['BattingAVG'].max()
)

wk_score_df['SR_Norm'] = (
    wk_score_df['BattingS/R'] /
    wk_score_df['BattingS/R'].max()
)

In [94]:
wk_score_df['PerformanceScore'] = (
    0.50 * wk_score_df['Runs_Norm'] +
    0.25 * wk_score_df['Avg_Norm'] +
    0.25 * wk_score_df['SR_Norm']
) * 100

In [95]:
wk_score_df[
[
'Name',
'ValueinCR',
'RunsScored',
'PerformanceScore'
]
].sort_values(
by='PerformanceScore',
ascending=False
).head(10)

                Name  ValueinCR  RunsScored  PerformanceScore
121         MS Dhoni      12.00      4746.0         92.757402
193         KL Rahul      17.00      3273.0         81.479669
123    Ambati Rayudu       6.75      3916.0         77.335730
79    Dinesh Karthik       5.50      4046.0         77.133825
48      Sanju Samson      14.00      3068.0         69.366284
169     Rishabh Pant      16.00      2498.0         68.646955
50       Jos Buttler      10.00      1968.0         63.451952
199  Quinton de Kock       6.75      2256.0         61.401660
227  Wriddhiman Saha       1.90      2110.0         55.924409
5     Jonny Bairstow       6.75      1038.0         55.757238

In [96]:
wk_final = wk_score_df[
['Name','Type','ValueinCR','PerformanceScore']
].copy()

In [97]:
master_df = pd.concat([
    batsmen_final,
    bowlers_final,
    allrounders_final,
    wk_final
], ignore_index=True)

In [98]:
master_df['Type'].value_counts()

Type
Bowler           53
All-Rounder      43
Wicket-Keeper    21
Batsman          19
Name: count, dtype: int64

In [99]:
best_batsmen = master_df[
    master_df['Type']=='Batsman'
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(4)

In [100]:
best_wk = master_df[
    master_df['Type']=='Wicket-Keeper'
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(1)

In [101]:
best_allrounders = master_df[
    master_df['Type']=='All-Rounder'
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(3)

In [102]:
best_bowlers = master_df[
    master_df['Type']=='Bowler'
].sort_values(
    by='PerformanceScore',
    ascending=False
).head(4)

In [103]:
recommended_squad = pd.concat([
    best_batsmen,
    best_wk,
    best_allrounders,
    best_bowlers
])

In [104]:
recommended_squad['ValueinCR'].sum()

np.float64(121.60000000000001)

In [105]:
recommended_squad['PerformanceScore'].sum()

np.float64(991.3302577624036)

In [106]:
recommended_squad

                  Name           Type  ValueinCR  PerformanceScore
5          Virat Kohli        Batsman      15.00         91.543761
13        David Warner        Batsman       6.25         88.816615
1       Shikhar Dhawan        Batsman       8.25         85.659253
7         Rohit Sharma        Batsman      16.00         82.934223
125           MS Dhoni  Wicket-Keeper      12.00         92.757402
90        Dwayne Bravo    All-Rounder       4.40         73.697199
88     Ravindra Jadeja    All-Rounder      16.00         72.017066
99        Sunil Narine    All-Rounder       6.00         68.623470
25   Bhuvneshwar Kumar         Bowler       4.20         87.494300
33    Yuzvendra Chahal         Bowler       6.50         86.979583
42      Jasprit Bumrah         Bowler      12.00         83.948985
67         Rashid Khan         Bowler      15.00         76.858401

In [107]:
recommended_squad.sort_values(
    by='ValueinCR',
    ascending=False
)

                  Name           Type  ValueinCR  PerformanceScore
7         Rohit Sharma        Batsman      16.00         82.934223
88     Ravindra Jadeja    All-Rounder      16.00         72.017066
5          Virat Kohli        Batsman      15.00         91.543761
67         Rashid Khan         Bowler      15.00         76.858401
125           MS Dhoni  Wicket-Keeper      12.00         92.757402
42      Jasprit Bumrah         Bowler      12.00         83.948985
1       Shikhar Dhawan        Batsman       8.25         85.659253
33    Yuzvendra Chahal         Bowler       6.50         86.979583
13        David Warner        Batsman       6.25         88.816615
99        Sunil Narine    All-Rounder       6.00         68.623470
90        Dwayne Bravo    All-Rounder       4.40         73.697199
25   Bhuvneshwar Kumar         Bowler       4.20         87.494300

In [108]:
master_df.to_csv("IPL_Auction_Master.csv", index=False)

In [109]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.copilot',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.local',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'IPL dataset.ipynb',
 'IPL_Auction_Master.csv',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{9d043c1d-c5fc-11ed-9314-080027ec4824}.TM.blf',
 'NTUSER.DAT{9d043c1d-c5fc-11ed-9314-080027ec4824}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{9d043c1d-c5fc-11ed-9314-080027ec4824}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'pr.py',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [110]:
import os
print(os.getcwd())

C:\Users\DELL